name: Build and Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    # uses: Logius-standaarden/Automatisering/.github/workflows/build.yml@main
    uses: Geonovum/NL-ReSpec-template/.github/workflows/build.yml@main
